### ISSUE TITLE
Adjust plot x-axis tick labels to fall on full hours

### ISSUE THREAD

**Issue by mattldawson** [mattldawson/music_box_interactive#3]
Use an increment that matches a factor of an hour instead of some round number: 21600, 43200, 64800, 86400 instead of 20000, 40000, 60000, 80000.

**Comment by mattldawson** [comment]
Hi @s-omas - this is something one of the scientists requested - would you be able to handle this?

**Comment by s-omas** [comment]
Hi matt- I am working on it. I have adjusted the tick spacing to increments of hours, now I am trying to make the increments scale as the simulation length changes while still being in multiples of hours.

**Comment by mattldawson** [comment]
That's awesome - thanks!
